spring.application.name=open-ai

spring.ai.openai.api-key=${OPENAI_API_KEY}

# src/main/resources/application.properties
app.quote.prompt-template=Generate a short, motivational quote about 
app.model=gpt-4.1-nano
app.max-tokens=30