spring.application.name=open-ai

spring.ai.openai.api-key=${OPENAI_API_KEY}
# src/main/resources/application.properties
app.quote.prompt-template=Generate a short, motivational quote with max_tokens=30 about 
app.sarvam.model=sarvam-m
app.model=gpt-4.1-nano
app.max-tokens=30
app.sarvam.ai.token=sk_tiwmtg5f_Q5CIGsyOBp4DpOsUNAau99Kr