spring.application.name=open-ai

#spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.api-key=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
#spring.ai.openai.api-key=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
#spring.ai.openai.api-key=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

# src/main/resources/application.properties
app.quote.prompt-template=Generate a short, motivational quote with max_tokens=30 about 
app.sarvam.model=sarvam-m
app.model=gpt-4.1-nano
app.max-tokens=30
app.sarvam.ai.token=sk_tiwmtg5f_Q5CIGsyOBp4DpOsUNAau99Kr